namespace Logic.Levels
{
    public enum TypesOfCards
    {
        BellsWithBow,
        BigDeer,
        BrownDeer,
        DeerWithGift,
        BlueSnowflake,
        ChristmasWreath,
        GreenGift,
        YellowGift,
        Mittens,
        PurpleBall,
        SockWithGifts,
        SockWithoutGifts,
        StrawberryPie,
        TwigWithBerriesOne,
        TwigWithBerriesTwo,
        BlueGift,
        GreenChristmasTree,
        RedBag,
        SantaClausWithBag,
        Snowman,
        StandingDeer,
        Rocket,
        Skates,
        BellsWithBranch,
        CandleAndBalls,
        Garland,
        Gingerbread,
        GreenGiftWithBow,
        RedCandle,
        RedChristmasBall,
        RedLollipop,
        RedSockWithChristmasTree,
        SleighWithGifts
    }
}